// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c95f8b9b-7aff-422d-bbdc-8799364b67d7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nvujAaouU",
    "aws_user_pools_web_client_id": "77hl74mvkkakkci46edke21kvk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://facadajwxvgsvfthacjdzwrp7m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "donors-app7359da888415488a954d64f04199172d-devtwo",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "donors-app-20191031140617-hostingbucket-devtwo",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d19q2oqdt3tlj1.cloudfront.net"
};


export default awsmobile;
